#pragma once


#define SAMPLING_RATE 44100


typedef enum{
    PARAM_ID_VOLUME,
    PARAM_ID_WAVEFORM,
    N_PARAMS
} ParamID;

enum class WaveformType{
    WAVEFORM_SAWTOOTH,
    WAVEFORM_SQUARE,
    WAVEFORM_PULSE,
    WAVEFORM_DOUBLE_SINE,
    WAVEFORM_SAW_PULSE,
    WAVEFORM_RESONANCE_I_SAWTOOTH,
    WAVRFORM_RESONANCE_II_TRIANGLE,
    WAVEFORM_RESONANCE_III_TRAPEZOID,
    N_WAVEFORMS
};