#pragma once


#define SAMPLING_RATE 44100
#define EPSILON 0.00001


typedef enum{
    PARAM_ID_VOLUME,
    PARAM_ID_WAVEFORM,
    PARAM_ID_DCW,
    N_PARAMS
} ParamID;

enum class Waveform{
    SAWTOOTH,
    SQUARE,
    PULSE,
    DOUBLE_SINE,
    SAW_PULSE,
    RESONANCE_SAWTOOTH,
    RESONANCE_TRIANGLE,
    RESONANCE_TRAPEZOID,
    N_WAVEFORMS
};