#pragma once


#define SAMPLING_RATE 44100
#define EPSILON 0.00001

#define N_OPT_EG_SUSTAIN_POINT 8
#define N_OPT_EG_END_POINT 7


typedef enum{
    PARAM_ID_VOLUME,
    PARAM_ID_WAVEFORM,
    PARAM_ID_DCW,

    // DCA EG
    PARAM_ID_DCA_EG_RATE_1,
    PARAM_ID_DCA_EG_RATE_2,
    PARAM_ID_DCA_EG_RATE_3,
    PARAM_ID_DCA_EG_RATE_4,
    PARAM_ID_DCA_EG_RATE_5,
    PARAM_ID_DCA_EG_RATE_6,
    PARAM_ID_DCA_EG_RATE_7,
    PARAM_ID_DCA_EG_RATE_8,
    PARAM_ID_DCA_EG_LVL_0,
    PARAM_ID_DCA_EG_LVL_1,
    PARAM_ID_DCA_EG_LVL_2,
    PARAM_ID_DCA_EG_LVL_3,
    PARAM_ID_DCA_EG_LVL_4,
    PARAM_ID_DCA_EG_LVL_5,
    PARAM_ID_DCA_EG_LVL_6,
    PARAM_ID_DCA_EG_LVL_7,
    PARAM_ID_DCA_EG_LVL_8,
    PARAM_ID_DCA_EG_SUSTAIN_POINT,
    PARAM_ID_DCA_EG_END_POINT,

    N_PARAMS
} ParamID;

enum class Waveform{
    SAWTOOTH,
    SQUARE,
    PULSE,
    DOUBLE_SINE,
    SAW_PULSE,
    RESONANCE_SAWTOOTH,
    RESONANCE_TRIANGLE,
    RESONANCE_TRAPEZOID,
    N_WAVEFORMS
};